# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:   
  win: circleci/windows@2.3.0
jobs:
  build:  
    working_directory: ~/mern-starter
    #machine:
    #  - image: ubuntu-1604:201903-01     
    docker: 
      - image: circleci/node:10.16.3 
      - image: mongo:4.2.0
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'  
#workflows:
#   main:   
#   jobs:      
#    - build
