version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:9.8      
    steps:
     - checkout
     - restore_cache:
        key: npm-install-{{ .Branch}}-{{ checksum "package.json" }}      
     - run: npm install
     - save_cache:
        key: npm-install-{{ .Branch}}-{{ checksum "package.json" }}
        paths: 
          -node_modules    
     - run:
        command:
          - cd .. #"~/home/circleci/project/-node_modules/.bin/eslint ./"
          - ls -R 
        

        
      
