version: 2.1
working_directory: ~/repo
orbs:
  heroku: circleci/heroku@1.0.1
jobs:
  build:
    docker:
      - image: circleci/node:9.8      
    steps:
     - checkout
     - restore_cache:
        key: npm-install-{{ .Branch}}-{{ checksum "package.json" }}      
     - run: npm install
     - save_cache:
        key: npm-install-{{ .Branch}}-{{ checksum "package.json" }}
        paths: 
          -node_modules   
     - run: ./node_modules/.bin/eslint ./     
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install      
      - heroku/deploy-via-git

workflows:
  heroku_deploy:
    jobs:
      - build     
      - deploy:
          requires:
            - build # only run deploy-via-git job if the build job has completed           
          filters:
            branches:
              only: master
              
