# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:   
  win: circleci/windows@2.3.0
jobs:
  build:  
    working_directory: ~/mern-starter       
    docker: 
      - image: circleci/node:10.16.3 
      - image: mongo:4.2.0
    steps:
      -checkout
      - run:          
          name: Update npm
          command: 'sudo npm install -g npm@latest' #updating npm
      - restore_cache:          
           key: dependency-cache-{{ checksum "package-lock.json" }} #skipping npm installing in new tests    
           keys: dependency-cache-
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }} 
          paths: ./node_modules
workflows:
   main:   
    jobs:      
      - build
